# Generated by Django 3.2.5 on 2022-03-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220330_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type_of_file',
            field=models.CharField(choices=[('Финансовая отчетность', 'Финансовая отчетность'), ('Корпоративные события', 'Корпоративные события'), ('Разрешительные документы', 'Разрешительные документы')], default=('Финансовая отчетность', 'Финансовая отчетность'), max_length=30),
        ),
    ]
