# Generated by Django 3.2.5 on 2022-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_documents_type_of_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type_of_file',
            field=models.CharField(choices=[('Финансовая отчетность', 'Финансовая отчетность'), ('Корпоративные документы', 'Корпоративные документы'), ('Разрешительные документы', 'Разрешительные документы')], default=('Финансовая отчетность', 'Финансовая отчетность'), max_length=30),
        ),
    ]
